//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Control {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Control() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Application.Resources.Control", typeof(Control).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İptal.
        /// </summary>
        public static string LabelGridCancel {
            get {
                return ResourceManager.GetString("LabelGridCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LabelGridCommands {
            get {
                return ResourceManager.GetString("LabelGridCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        public static string LabelGridDelete {
            get {
                return ResourceManager.GetString("LabelGridDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncelle.
        /// </summary>
        public static string LabelGridEdit {
            get {
                return ResourceManager.GetString("LabelGridEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet.
        /// </summary>
        public static string LabelGridUpdate {
            get {
                return ResourceManager.GetString("LabelGridUpdate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Seçiniz.
        /// </summary>
        public static string LabelSelect {
            get {
                return ResourceManager.GetString("LabelSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be less than 10000..
        /// </summary>
        public static string LessThan10000 {
            get {
                return ResourceManager.GetString("LessThan10000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorumlu kişi, sunucuya başarılı bir şekilde eklendi..
        /// </summary>
        public static string MessageAddManager {
            get {
                return ResourceManager.GetString("MessageAddManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kişiyi ekleyemezsiniz. Server üzerinde zaten mevcut..
        /// </summary>
        public static string MessageCouldNotAddManager {
            get {
                return ResourceManager.GetString("MessageCouldNotAddManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorumlu kişi kaydı başarıyla yaratıldı..
        /// </summary>
        public static string MessageCreateManager {
            get {
                return ResourceManager.GetString("MessageCreateManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server başarıyla kaydedildi..
        /// </summary>
        public static string MessageCreateServer {
            get {
                return ResourceManager.GetString("MessageCreateServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorumlu kişi başarıyla silindi..
        /// </summary>
        public static string MessageDeleteManager {
            get {
                return ResourceManager.GetString("MessageDeleteManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server kaydı başarıyla silindi..
        /// </summary>
        public static string MessageDeleteServer {
            get {
                return ResourceManager.GetString("MessageDeleteServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorumlu, server üzerinden başarıyla kaldırıldı..
        /// </summary>
        public static string MessageRemoveManager {
            get {
                return ResourceManager.GetString("MessageRemoveManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorumlu kişi kaydı başarıyla güncellendi..
        /// </summary>
        public static string MessageUpdateManager {
            get {
                return ResourceManager.GetString("MessageUpdateManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can not exceed {1} characters..
        /// </summary>
        public static string ValidationMaxLength {
            get {
                return ResourceManager.GetString("ValidationMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can only be numeric..
        /// </summary>
        public static string ValidationNumeric {
            get {
                return ResourceManager.GetString("ValidationNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required..
        /// </summary>
        public static string ValidationRequired {
            get {
                return ResourceManager.GetString("ValidationRequired", resourceCulture);
            }
        }

        public static string UpdatePing
        {
            get
            {
                return ResourceManager.GetString("UpdatePing", resourceCulture);
            }
        }

        public static string AddRelationServer
        {
            get
            {
                return ResourceManager.GetString("AddRelationServer", resourceCulture);
            }
        }

        
    }
}
