//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Elmah {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Elmah() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Application.Resources.Elmah", typeof(Elmah).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        internal static string LabelApplication {
            get {
                return ResourceManager.GetString("LabelApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App. Expression.
        /// </summary>
        internal static string LabelApplicationExpression {
            get {
                return ResourceManager.GetString("LabelApplicationExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App. Expression2.
        /// </summary>
        internal static string LabelApplicationExpression2 {
            get {
                return ResourceManager.GetString("LabelApplicationExpression2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elmah.
        /// </summary>
        internal static string LabelElmah {
            get {
                return ResourceManager.GetString("LabelElmah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        internal static string LabelEndDate {
            get {
                return ResourceManager.GetString("LabelEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorId.
        /// </summary>
        internal static string LabelErrorIdString {
            get {
                return ResourceManager.GetString("LabelErrorIdString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Count.
        /// </summary>
        internal static string LabelExceptionCount {
            get {
                return ResourceManager.GetString("LabelExceptionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Limit.
        /// </summary>
        internal static string LabelExceptionNumber {
            get {
                return ResourceManager.GetString("LabelExceptionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Request.
        /// </summary>
        internal static string LabelExceptionRequest {
            get {
                return ResourceManager.GetString("LabelExceptionRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Type.
        /// </summary>
        internal static string LabelExceptionType {
            get {
                return ResourceManager.GetString("LabelExceptionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands.
        /// </summary>
        internal static string LabelGridCommands {
            get {
                return ResourceManager.GetString("LabelGridCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        internal static string LabelHost {
            get {
                return ResourceManager.GetString("LabelHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Creation Date.
        /// </summary>
        internal static string LabelKayitYaratmaTarihi {
            get {
                return ResourceManager.GetString("LabelKayitYaratmaTarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Address.
        /// </summary>
        internal static string LabelMailAddress {
            get {
                return ResourceManager.GetString("LabelMailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string LabelMessage {
            get {
                return ResourceManager.GetString("LabelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Msg Not Like.
        /// </summary>
        internal static string LabelMessageNotLike {
            get {
                return ResourceManager.GetString("LabelMessageNotLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence.
        /// </summary>
        internal static string LabelSequence {
            get {
                return ResourceManager.GetString("LabelSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string LabelSource {
            get {
                return ResourceManager.GetString("LabelSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string LabelStartDate {
            get {
                return ResourceManager.GetString("LabelStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Interval(dk).
        /// </summary>
        internal static string LabelTimeInterval {
            get {
                return ResourceManager.GetString("LabelTimeInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception.
        /// </summary>
        internal static string LabelType {
            get {
                return ResourceManager.GetString("LabelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string LabelUser {
            get {
                return ResourceManager.GetString("LabelUser", resourceCulture);
            }
        }
    }
}
