//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Envanter {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Envanter() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Application.Resources.Envanter", typeof(Envanter).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açıklama.
        /// </summary>
        internal static string LabelAciklama {
            get {
                return ResourceManager.GetString("LabelAciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makina Adı.
        /// </summary>
        internal static string LabelComputerName {
            get {
                return ResourceManager.GetString("LabelComputerName", resourceCulture);
            }
        }
       
        /// <summary>
        ///   Looks up a localized string similar to Yönetici.
        /// </summary>
        internal static string LabelIsAdmin {
            get {
                return ResourceManager.GetString("LabelIsAdmin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı.
        /// </summary>
        internal static string LabelKullanici {
            get {
                return ResourceManager.GetString("LabelKullanici", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı.
        /// </summary>
        internal static string LabelKullaniciAd {
            get {
                return ResourceManager.GetString("LabelKullaniciAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı E -Mail.
        /// </summary>
        internal static string LabelKullaniciEmail {
            get {
                return ResourceManager.GetString("LabelKullaniciEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokasyon.
        /// </summary>
        internal static string LabelLokasyon {
            get {
                return ResourceManager.GetString("LabelLokasyon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokasyon.
        /// </summary>
        internal static string LabelLokasyonAd {
            get {
                return ResourceManager.GetString("LabelLokasyonAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating System.
        /// </summary>
        internal static string LabelOperatingSystem {
            get {
                return ResourceManager.GetString("LabelOperatingSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşletim Sistemi.
        /// </summary>
        internal static string LabelOperatingSystemAd {
            get {
                return ResourceManager.GetString("LabelOperatingSystemAd", resourceCulture);
            }
        }

        internal static string LabelPingYapilsinMi
        {
            get {
                return ResourceManager.GetString("LabelPingYapilsinMi", resourceCulture);
            }
        }
      
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        internal static string LabelServer {
            get {
                return ResourceManager.GetString("LabelServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server IP.
        /// </summary>
        internal static string LabelServerIp {
            get {
                return ResourceManager.GetString("LabelServerIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Tipi.
        /// </summary>
        internal static string LabelServerTipi {
            get {
                return ResourceManager.GetString("LabelServerTipi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Tipi.
        /// </summary>
        internal static string LabelServerTipiAd {
            get {
                return ResourceManager.GetString("LabelServerTipiAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorumlu.
        /// </summary>
        internal static string LabelYonetici {
            get {
                return ResourceManager.GetString("LabelYonetici", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorumlu Adı.
        /// </summary>
        internal static string LabelYoneticiAdi {
            get {
                return ResourceManager.GetString("LabelYoneticiAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorumlu E-Mail.
        /// </summary>
        internal static string LabelYoneticiEmail {
            get {
                return ResourceManager.GetString("LabelYoneticiEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunucu başarı ile yaratıldı..
        /// </summary>
        internal static string MessageCreateServer {
            get {
                return ResourceManager.GetString("MessageCreateServer", resourceCulture);
            }
        }
    }
}
