//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class IslemLog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IslemLog() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Application.Resources.IslemLog", typeof(IslemLog).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation.
        /// </summary>
        internal static string LabelAddedNew {
            get {
                return ResourceManager.GetString("LabelAddedNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity Field Name.
        /// </summary>
        internal static string LabelEntityFieldName {
            get {
                return ResourceManager.GetString("LabelEntityFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity Id Value.
        /// </summary>
        internal static string LabelEntityIdValue {
            get {
                return ResourceManager.GetString("LabelEntityIdValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity Name.
        /// </summary>
        internal static string LabelEntityName {
            get {
                return ResourceManager.GetString("LabelEntityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Name.
        /// </summary>
        internal static string LabelIslemAdi {
            get {
                return ResourceManager.GetString("LabelIslemAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem.
        /// </summary>
        internal static string LabelIslemLog {
            get {
                return ResourceManager.GetString("LabelIslemLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string LabelKullaniciAdi {
            get {
                return ResourceManager.GetString("LabelKullaniciAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Value.
        /// </summary>
        internal static string LabelNewValue {
            get {
                return ResourceManager.GetString("LabelNewValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Value.
        /// </summary>
        internal static string LabelOldValue {
            get {
                return ResourceManager.GetString("LabelOldValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Type.
        /// </summary>
        internal static string LabelOperationType {
            get {
                return ResourceManager.GetString("LabelOperationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Message Date.
        /// </summary>
        internal static string LabelRequestMessageDate {
            get {
                return ResourceManager.GetString("LabelRequestMessageDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Status Id.
        /// </summary>
        internal static string LabelResponseStatusId {
            get {
                return ResourceManager.GetString("LabelResponseStatusId", resourceCulture);
            }
        }
    }
}
